name: tfe-train
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.26
  - scikit-learn=1.5
  - packaging
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - --find-links https://data.dgl.ai/wheels/cu121/repo.html
      - torch==2.4.1+cu124
      - dgl==1.1.3+cu121
